#%RAML 1.0
title: More2Life
baseUri: https://m2l-server.herokuapp.com/api
mediaType: application/json

types:
  FeedItem:
    type: object
    properties:
      _id:
        type: string
        description: The unique identifier of the item
      title:
        type: string
        description: The title / name of the item
      description:
        type: string
        description: The description of the content in the item
      feedImageUrl:
        type: string
        description: The url to the image to be shown in the feed
      type:
        type: string
        enum: [story, event, listing]
      isActive:
        type: boolean
        description: Should be displayed in the Feed
      createdAt:
        type: string
        description: The date the feed item document was created
      images?:
        type: string[]
        description: URLs to gallery images for this feed item
  Story:
    type: FeedItem
    properties:
      videoUrl?:
        description: The url to the video stream
        type: string
      publishDate:
        description: The date the story was published
        type: string
      views?:
        description: The number of times the video was viewed
        type: integer
  Event:
    type: FeedItem
    properties:
      address:
        type: string
        description: The printable, one-line street address of the location.
      area:
        type: string
        description: The general area of the event, i.e., City, ST
      multiLineAddress:
        type: string[]
        description: Individual lines of the address, for printing across multiple lines
      latitude:
        type: string
        description: Latitude as String
      longitude:
        type: string
        description: Longitude as String
      venueName:
        type: string
        description: Name of the venue, i.e. Marriott Center
      eventUrl:
        type: string
        description: URL for eventbrite.com web page
      resourceUri:
        type: string
        description: URI for requesting this resource from Eventbrite API
      startTime:
        type: string
        description: Start date & time in local time of the event. Sorry it's a string.
      endTime:
        type: string
        description: End date & time in local time of the event. Sorry it's a string.
  Listing:
    type: FeedItem
    properties:
      vendorId:
        type: integer
        description: The ID of the item on the vendor (Shopify)
      handle:
        type: string
        description: The unique Shopify handle of the product
      lastUpdatedAt:
        type: string
        description: The date the item was last updated on the vendor's system
      price:
        type: string
        description: The price of the item for labelling purposes
  Donation:
      type: FeedItem
      properties:
        vendorId:
          type: integer
          description: The ID of the item on the vendor (Shopify)
        handle:
          type: string
          description: The unique Shopify handle of the product
        lastUpdatedAt:
          type: string
          description: The date the item was last updated on the vendor's system
        price:
          type: string
          description: The 'price' of the item for labelling purposes (always has value "Donation")
  EventWebhook:
    properties:
      api_url:
        type: string
        description: URL for the updated resource
      config:
        type: object
        properties:
          action:
            type: string
            description: Name of the event that occurred on Eventbrite
          endpoint_url:
            type: string
            description: The URL to which Eventbrite will POST the hook body
          user_id: string
          webhook_id: string

/feedItems:
  description: Get a feed of content
  displayName: Feed
  get:
    queryParameters:
      count?: integer
      index?: integer
      type?:
        enum: [story, event, listing, donation]
        description: Used to request feed items of only one type
      isActive?:
        type: boolean
        description: Active feedItems should be shown in the app.
    headers:
      Accept-Language:
        description: The language the application is running in. Titles, descriptions, and any other user facing string should come down from the server translated in that language.
    responses:
      200:
        body:
          application/json:
            type: FeedItem[]
            example: !include /examples/feed-example.json

/donationBuckets:
  description: Get the donation buckets used for arbitrary donation amounts
  displayName: Donation Bucket
  get:
    headers:
      Accept-Language:
        description: The language the application is running in. Titles, descriptions, and any other user facing string should come down from the server translated in that language.
    responses:
      200:
        body:
          application/json:
            type: DonationBucket[]
            example: !include /examples/donationBucket-example.json

/webhooks/eventbrite:
  /create:
    description:
      POST an event.created webhook from Eventbrite.
      [Eventbrite docs](https://www.eventbrite.com/developer/v3/api_overview/webhooks/)
      [Configure here](https://www.eventbrite.com/myaccount/webhooks/)
    displayName: Create Event Webhook
    post:
      body:
        application/json:
          type: EventWebhook
          example: !include /examples/eventbritewebhook.json
  /update:
    description:
      POST an event.updated webhook from Eventbrite.
      [Eventbrite docs](https://www.eventbrite.com/developer/v3/api_overview/webhooks/)
      [Configure here](https://www.eventbrite.com/myaccount/webhooks/)
    displayName: Update Event Webhook
    post:
      body:
        application/json:
          type: EventWebhook
          example: !include /examples/eventbritewebhook.json
