#%RAML 1.0
title: More2Life API
baseUri: https://m2l-server.herokuapp.com/api
mediaType: application/json

types:
  FeedItem:
    type: object
    properties:
      _id:
        type: string
        description: The unique identifier of the item
      title:
        type: string
        description: The title / name of the item
      description:
        type: string
        description: The description of the content in the item
      index:
        type: integer
        description: The position of the item in the feed. Used for sorting and paging
      type:
        type: string
        enum: [Video, Event, Listing]
      isActive:
        type: boolean
        description: Should be displayed in the Feed
  Video:
    type: FeedItem
    properties:
      previewImageUrl:
        description: The url to the image for the frame of the video to show as a preview
        type: string
      videoUrl:
        description: The url to the video stream
        type: string
      publishDate:
        description: The date the video was published
        type: string
      views:
        description: The number of times the video was viewed
        type: integer
  Event:
    type: FeedItem
    properties:
      address:
        type: string
        description: The printable, one-line street address of the location.
      area:
        type: string
        description: The general area of the event, i.e., City, ST
      multiLineAddress:
        type: string[]
        description: Individual lines of the address, for printing across multiple lines
      latitude:
        type: string
        description: Latitude as String
      longitude:
        type: string
        description: Longitude as String
      venueName:
        type: string
        description: Name of the venue, i.e. Marriott Center
      eventUrl:
        type: string
        description: URL for eventbrite.com web page
      resourceUri:
        type: string
        description: URI for requesting this resource from Eventbrite API
      imageUrl:
        type: string
        description: URL to the image to display for the event
      startTime:
        type: string
        description: Start date & time in local time of the event. Sorry it's a string.
      endTime:
        type: string
        description: End date & time in local time of the event. Sorry it's a string.
  Listing:
    type: FeedItem
    properties:
      Product:
        type: Product
        description: The product featured in the feed Listing
      previewImageUrl:
        type: string
        description: The url to the image for the product to show as a preview
  Product:
    description: A product to be sold in the store
    properties:
      _id:
        type: string
        description: The unique identifier of the product
      price:
        type: number
        format: float
        description: The price of the item

/feedItems:
  description: Get a feed of content
  displayName: Feed
  get:
    queryParameters:
      count?: integer
      index?: integer
      type?:
        enum: [video, event, listing]
        description: Used to request feed items of only one type
    headers:
      Accept-Language:
        description: The language the application is running in. Titles, descriptions, and any other user facing string should come down from the server translated in that language.
    responses:
      200:
        body:
          application/json:
            type: FeedItem[]
            example: !include /examples/feed-example.json
